"""initial tables

Revision ID: 35932376d4e3
Revises: a4fa06eb27e7
Create Date: 2026-08-23 02:04:32.416643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35932376d4e3'
down_revision = 'a4fa06eb27e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
